main: de.carina.pixelsjump.PixelsJump
api-version: 1.19
name: PixelsJump
version: 1.4.3
description: PixelsJump Remastered for Paper
author: Carina-Sophie Schoppe
commands:
  pixelsjump:
    description: PixelsJump Remastered for Paper
    usage: /pixelsjump <command> <arguments>
    aliases: [ pixelsjump, pj, pixeljump, pixels-jump, pixel-jump, p-j ]
